---
# tasks file for ansible-mapr_python

- name: install libxml and dependencies for the xml module
  yum: name="{{item}}" state=present
  with_items:
    - python-devel
    - python-setuptools
  when: ansible_distribution in ('CentOS','RedHat','Amazon')
  environment: proxy_env

- name: install pip (Amazon Linux)
  yum: name=python-pip state=present
  environment: proxy_env
  when: ansible_distribution in ('Amazon')

- name: install pip (RHEL, CentOS)
  command: easy_install pip
  environment: proxy_env
  when: ansible_distribution in ('CentOS', 'RedHat')

- name: install requests
  pip: name=requests state=present
  environment: proxy_env
