---
# tasks file for ansible-mapr_python

- name: install libxml and dependencies for the xml module
  yum: name="{{item}}" state=present
  with_items:
    - python-devel
    - python-setuptools
  when: ansible_distribution in ('CentOS','RedHat','Amazon')
  environment: proxy_env

- name: install pip (Amazon Linux)
  yum: name=python-pip state=present
  environment: proxy_env
  when: ansible_distribution in ('Amazon')

- name: install pip (RHEL, CentOS)
  command: easy_install pip
  environment: proxy_env
  when: ansible_distribution in ('CentOS', 'RedHat')

- name: install requests
  pip: name=requests state=present
  environment: proxy_env

- name: install MySQL python module
  yum: name=MySQL-python state=installed
  when: ansible_distribution in ("CentOS", "RedHat")
  environment: proxy_env

- name: install MySQL python module (2.6 and 2.7)
  yum: name={{item}} state=installed
  when: ansible_distribution in ("Amazon")
  with_items:
    - MySQL-python26
    - MySQL-python27
  environment: proxy_env

- name: install MySQL python module  on Debian derived OSes
  apt: name=python-mysqldb state=installed
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  environment: proxy_env
